quarkus:
  hibernate-orm:
    implicit-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database:
      generation: drop-and-create
    log:
      sql: true

"%dev":
  quarkus:
    http:
      port: 8080

"%test":
  quarkus:
    messaging:
      kafka:
        devservices:
          enabled: false

mp:
  messaging:
    incoming:
      createOrder:
        connector: smallrye-kafka
        topic: createOrder
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      updateLocation:
        connector: smallrye-kafka
        topic: updateLocation
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      assignDelivery:
        connector: smallrye-kafka
        topic: assignDelivery
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

    outgoing:
      createOrder:
        connector: smallrye-kafka
        topic: createOrder
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      updateLocation:
        connector: smallrye-kafka
        topic: updateLocation
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
      assignDelivery:
        connector: smallrye-kafka
        topic: assignDelivery
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer