quarkus:
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database:
      generation: drop-and-create
    log:
      sql: true

  mongodb:
    database: food
    uuid-representation: standard
#    devservices:
#      image-name: mongo:4.4.29

  http:
    root-path: /api

#mp:
#  messaging:
#    outgoing:
#      orderCreated:
#        merge: true
#        value:
#          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#    incoming:
#      createOrder:
#        value:
#          deserializer: com.thehuginn.messaging.dto.Deserializer

"%dev":
  quarkus:
    http:
      port: 8080

    kafka:
      devservices:
        port: 9092

"%test":
  quarkus:
    hibernate-orm:
      sql-load-script: no-file
