quarkus:
  hibernate-orm:
    implicit-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database:
      generation: drop-and-create
    log:
      sql: true

"%dev":
  quarkus:
    http:
      port: 8080