quarkus:
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database:
      generation: drop-and-create
    log:
      sql: true

  mongodb:
    database: food
    uuid-representation: standard
    
"%dev":
  quarkus:
    http:
      port: 8080