quarkus:
  http:
    root-path: /api
    test-port: 8083
  rest-client:
    "com.thehuginn.integration.OrderServiceMicroservice":
      url: http://localhost:8080

"%dev":
  quarkus:
    http:
      port: 8082

    kafka:
      devservices:
        port: 9092