quarkus:
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database:
      generation: drop-and-create
    log:
      sql: true

  http:
    root-path: /api
    test-port: 8085

"%dev":
  quarkus:
    http:
      port: 8084

    kafka:
      devservices:
        port: 9092

"%test":
  quarkus:
    hibernate-orm:
      sql-load-script: no-file